//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassportManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisaApplication()
        {
            this.CancellationCharges = 0;
            this.Status = "Approved";
        }
    
        public string VisaID { get; set; }
        public string UserID { get; set; }
        public string PassportNumber { get; set; }
        public string Country { get; set; }
        public string Occupation { get; set; }
        public System.DateTime DateOfApplication { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime DateOfExpiry { get; set; }
        public int RegistrationCost { get; set; }
        public int CancellationCharges { get; set; }
        public string Status { get; set; }
    
        public virtual PassportApplication PassportApplication { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
