//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassportManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaCancellation
    {
        public string UserID { get; set; }
        public string VisaNumber { get; set; }
        public int CancellationCharges { get; set; }
        public string Status { get; set; }
    
        public virtual VisaApplication VisaApplication { get; set; }
    }
}
